image: ubuntu:16.04

build:
  stage: build
  script:
    - "echo 'Building...'"
    - "echo $PRIVATE_KEY"
    
test:
  stage: test
  script:
    - "echo 'Testing...'"
    - "echo $PRIVATE_KEY"
    
deploy:
  stage: deploy
  script:
    - "echo 'Deploying...'"
    - "echo $PRIVATE_KEY"
  only:
    - master
 
